version: "3.8"

services:
  php-apache:
    build:
      context: ./php-apache
      args:
        - WWW_USER_ID=${WWW_USER_ID}
        - WWW_GROUP_ID=${WWW_GROUP_ID}
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ../:/var/www/html
    depends_on:
      - mysql

  mysql:
   build:
     context: ./container/mysql
     dockerfile: Dockerfile
   environment:
     MYSQL_DATABASE: wilddish
     MYSQL_USER: suda
     MYSQL_PASSWORD: root
     MYSQL_ROOT_PASSWORD: root
     TZ: "Asia/Tokyo"
   ports:
     - 3306:3306
   volumes:
     - ./mysql/logs:/var/log/mysql
     - ./container/mysql/init.d:/docker-entrypoint-initdb.d
     - ./container/mysql/conf.d:/etc/mysql/conf.d

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_PORT=3306
        - PMA_USER=root
        - PMA_PASSWORD=root
      links:
        - mysql
      ports:
        - 8087:80
      volumes:
        - /sessions
